spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=BancaWeb;trustServerCertificate=true
    username: sa
    password: Something20*
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: none
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
